### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by philoserf** [MachoThemes/decode-lite#125]
Last GitHub release is .13
Latest release.txt is .15

I notice because I cannot find the place to update copyright.

**Comment by cristianraiber** [comment]
@philoserf - what exactly are you looking to achieve?

**Comment by philoserf** [comment]
I was trying out the theme again. I had trouble finding where I had customized the copyright statement in the newer version. While looking for it I saw the github release was 1.13.0 https://github.com/MachoThemes/decode-lite/releases/tag/v3.13.0 while wordpress.org hosted release was 3.15.3 http://markpaulayers.com/wp-admin/theme-install.php?theme=decode

I saw a comment in one of the merges that the copyright had moved but didn't find it.
