### ISSUE TITLE
decode and woocommerce

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/decode-lite#131]
Decode with Woo Commerce – getting warnings for out-of-date templates Woo commerce for the following

    decode/woocommerce/checkout/form-checkout.php version 2.3.0 is out of date. The core version is 3.5.0,
    decode/woocommerce/checkout/review-order.php version 3.3.0 is out of date. The core version is 3.8.0,
    decode/woocommerce/checkout/terms.php,
    decode/woocommerce/content-product.php version 3.4.0 is out of date. The core version is 3.6.0,
    decode/woocommerce/content-single-product.php version 3.4.0 is out of date. The core version is 3.6.0,
    decode/woocommerce/loop/add-to-cart.php,
    decode/woocommerce/loop/loop-start.php,
    decode/woocommerce/myaccount/form-login.php version 3.4.0 is out of date. The core version is 3.6.0,
    decode/woocommerce/single-product/product-image.php version 3.3.2 is out of date. The core version is 3.5.1,
    decode/woocommerce/single-product/tabs/description.php,
    decode/woocommerce/single-product/tabs/tabs.php version 2.4.0 is out of date. The core version is 3.8.0

**Comment by mplusb** [comment]
https://wordpress.org/support/topic/update-for-out-of-date-templates/

**Comment by cristianraiber** [comment]
We aren't selling Decode PRO any longer
