### ISSUE TITLE
3.13 update breaks some things

### ISSUE THREAD

**Issue by IonRutz** [MachoThemes/decode-lite#96]
You probably already know this, but just in case: the 3.13 update to Decode breaks the loop, display of posts, leaving home and category pages blank below the header. The content div is populated, but is not visible. I\'m seeing this online and on my local dev system. The 3.12 version is working fine.

**Comment by robciucioan** [comment]
@IonRutz, can you tell me more details about this issue? Thank you!

**Comment by IonRutz** [comment]
The problem is in the media query (min-width 68.5em), because it goes away below that break point.
There is a bogus inline css declaration (which is why I couldn't find anything in style.css) that kicks in:
.site-main {width: 792% }
That's probably supposed to be 79.2%, but the problem goes away when I remove it using Inspect Element in FF. It's reported as "Inline stylesheet #8."

**Comment by IonRutz** [comment]
![edge over1200px](https://cloud.githubusercontent.com/assets/15014267/14849926/722f71de-0c7e-11e6-8fac-5cfd28010d6f.png)
![edge under1200px](https://cloud.githubusercontent.com/assets/15014267/14849927/72308664-0c7e-11e6-9378-57e618ca4316.png)
![ff over1080px](https://cloud.githubusercontent.com/assets/15014267/14849928/7237d6da-0c7e-11e6-96e4-e9cc109ed52e.png)
![ff under1080px](https://cloud.githubusercontent.com/assets/15014267/14849929/723c4288-0c7e-11e6-94f3-200d3e2e23b9.png)

**Comment by IonRutz** [comment]
poze din edge si firefox peste si sub 1200px respectiv 1080

**Comment by IonRutz** [comment]
"We are now up to v 3.14.2 and there is STILL a problem when the browser window gets past about 1200 px (68.5em). I keep having to reinstall 3.12 so that the blog will function properly.

Global search for 792% and change to 79.2%. Commit the update, and it's a done deal."

As prompted by Alan :D
